apiVersion: apps/v1 # バージョン1.9.0より前であればapps/v1beta2を使ってください
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.8 # nginxのバージョンを1.7.9から1.8に更新する
        ports:
        - containerPort: 80
